.Dd 1/6/14               \" DATE
.Dt timelapse 1      \" Program name and manual section number
.Os Darwin
.Sh NAME                 \" Section Header - required - don't modify 
.Nm timelapse
.Nd Create a video from still images.
.Sh SYNOPSIS             \" Section Header - required - don't modify
.Nm
.Fl h
.Nm
.Op Fl vn               \" [-vhn]
.Fl o Ar output       \" [-a path]
.Op Fl c Ar h264
.Op Fl p Ar h.264-profile
.Op Fl l Ar h.264-level
.Op Fl b Ar bitrate
path ...             \" arguments
.Nm
.Op Fl vn               \" [-vhn]
.Fl o Ar output       \" [-a path]
.Fl c Ar hevc
.Op Fl b Ar bitrate
path ...             \" arguments
.Nm
.Op Fl vn               \" [-vhn]
.Fl o Ar output       \" [-a path]
.Fl c Ar jpeg
.Op Fl q Ar jpeg-quality
.Op Fl b Ar bitrate
path ...             \" arguments
.Nm
.Op Fl vn               \" [-vhn]
.Fl o Ar output       \" [-a path]
.Fl c Ar prores442
path ...             \" arguments
.Nm
.Op Fl vn               \" [-vhn]
.Fl o Ar output       \" [-a path]
.Fl c Ar prores4444
path ...             \" arguments
.Sh DESCRIPTION          \" Section Header - required - don't modify
.Nm
creates a video from a sequence of images using AV Foundation. The path arguments may be files or directories.
Directories will be recursively traversed. All resulting images are sorted by full path into alphabetical
order and then assembled into the video.
.Pp
Note: Not all codecs are compatible with all file types, e.g. some require a .mov file.
.Pp
.Bl -tag -width -indent  \" Differs from above in tag removed
.It Fl b Ar bitrate , Fl Fl bitrate Ns = Ns Ar bitrate                \"-a flag as a list item
Set the target bitrate, expressed in megabits per second.
.It Fl c Ar name , Fl Fl codec Ns = Ns Ar name
Select the codec for the video file. Supported codecs are h264, hevc, jpeg, prores4444, and prores422.
.It Fl f Ar fps , Fl Fl framesPerSeconds Ns = Ns Ar fps
Set the frames per second. Must be an integer. 30 is the default.
.It Fl h , Fl Fl help
Display help and version number then exit.
.It Fl H Ar hgt , Fl Fl height Ns = Ns Ar hgt
Set the output height. Width will be calculated to preserve aspect ratio if omitted.
.It Fl l Ar num , Fl Fl level Ns = Ns Ar num
Set the h.264 level. Valid choices are 3.0, 3.1, 3.2, 4.0, 4.1 and auto. The default is auto.
.It Fl n , Fl Fl nodup
Ignore images which are identical to their predecessor.
.It Fl o Ar filename , Fl Fl output Ns = Ns Ar filename
The output filename. This is required. The filename suffix determines the format. Valid extensions are 
mp4, m4v, and mov. Unrecognized extensions use the MPEG4 filetype.
.It Fl p Ar name , Fl Fl profile Ns = Ns Ar name
Set the h.264 profile. Valid choices are baseline, main, and high. The default is main.
.It Fl P Ar filename , Fl Fl poster Ns = Ns Ar filename
The poster filename. The poster image is a JPEG taken from around the middle of the sequence. It will be
resized to the same dimensions as the movie. It will not be written if there are no valid images
after the midpoint.
.It Fl q Ar num , Fl Fl quality Ns = Ns Ar num
Set the JPEG quality. e.g. --quality=0.8
.It Fl v , Fl Fl verbose
Print verbose messages while operating.
.It Fl W Ar wid , Fl Fl width Ns = Ns Ar wid
Set the output width. Height will be calculated to preserve aspect ratio if omitted.
.El
.Pp
If there is a fatal error, a partially written file may be produced.
.\" .Sh ENVIRONMENT      \" May not be needed
.\" .Sh FILES                \" File used or created by the topic of the man page
.\" .Sh DIAGNOSTICS       \" May not be needed
.Sh WWW
The timelapse sources are managed at https://github.com/jimstudt/timelapse
.\" .Sh SEE ALSO
.\" .Sh BUGS              \" Document known, unremedied bugs
.\" .Sh HISTORY           \" Document history if command behaves in a unique manner
